services:
  qwinto:
    image: qwinto:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    environment:
      CI: "true"
      npm_config_confirm_modules_purge: "false"
      npm_config_store_dir: /pnpm/store
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    expose:
      - "5173"
    labels:
      - traefik.enable=true
      - traefik.docker.network=d20
      - traefik.http.routers.qwinto.rule=Host(`qwinto.localhost`)
      - traefik.http.routers.qwinto.entrypoints=web
      - traefik.http.services.qwinto.loadbalancer.server.port=5173
    networks:
      - d20

volumes:
  node_modules:
  pnpm_store:

networks:
  d20:
    external: true
