apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwinto
  namespace: d20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwinto
  template:
    metadata:
      labels:
        app: qwinto
    spec:
      containers:
        - name: qwinto
          image: d20/qwinto
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: qwinto
  namespace: d20
spec:
  selector:
    app: qwinto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qwinto
  namespace: d20
spec:
  ingressClassName: traefik
  rules:
    - host: qwinto.d20.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qwinto
                port:
                  number: 80
